import "dotenv/config";
import express from "express";
import cors from "cors";
import {z} from "zod";
import {ExpenseAnalysisWorkflow} from "./workflows/expense-analysis.workflow.js";
import {DarajaStkPushSkill} from "./skills/daraja-stk-push.skill.js";
const app=express();
app.use(cors({origin:process.env.ALLOWED_ORIGIN?.split(",") || true}));
app.use(express.json({limit:"1mb"}));
app.get("/api/health",(_req,res)=>res.json({status:"ok"}));
app.post("/api/analyze",async(req,res)=>{try{const input=z.object({statementText:z.string().min(10).max(100000),question:z.string().max(500).optional()}).parse(req.body);res.json(await new ExpenseAnalysisWorkflow().run(input));}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Request failed"});}});
app.post("/api/payments/stk-push",async(req,res)=>{try{const input=z.object({phone:z.string().regex(/^2547\d{8}$/),amount:z.number().positive().max(150000),accountReference:z.string().max(20).optional()}).parse(req.body);res.json(await new DarajaStkPushSkill().run(input));}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Request failed"});}});
export default app;
